ComplianceAsCode/compliance-operator

- CHANGELOG.md
- Makefile
- doc/contributor.md
Modify `prepare-release`, `push-release` make target to sync `ocp-0.1` branch to the latest release branch.
> Update release make target

- CHANGELOG.md
- deploy/role.yaml
Fix permission issue for `api-resource-collector`
> Modify api-resource collector permission

- .github/workflows/codeql-analysis.yml
- cmd/manager/resultserver.go
- pkg/profileparser/profileparser.go
This will scan the code base for vulnerabilities on each PR, and as a periodic job.
This also fixes some warnings coming from the tool.
> Add CodeQL analysis job

- CHANGELOG.md
- pkg/controller/compliancesuite/compliancesuite_controller_test.go
- pkg/utils/nodeutils.go
This PR fixs the issue on OVN cluster, it came to notice that MCO is rendering Machine Config using base64 encoding instead of urlencoding on OVN cluster, this PRs added a check on MachineConfig source, so that the remediation will work properly. BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2082431
> Bug 2082431: Fix MachineConfig base64 encoding issue on OVN cluster

- doc/crds.md
Let's use examples that contain all the required attributes.
> doc/crds.md: Use description in the TP example

- CHANGELOG.md
Added change log for PR: https://github.com/ComplianceAsCode/compliance-operator/pull/58
> Added changelog for fixing KubeletConfig issue

- doc/usage.md
Add upstream doc for `PriorityClass`
> Add upstream doc for PriorityClass

- doc/usage.md
This has been suggested by the operator-sdk developers. See also:
https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/subscription-config.md#resources
and:
https://sdk.operatorframework.io/docs/best-practices/managing-resources/
> doc: Document how to increase operator's memory limits

- enhancements/improve-kubeletconfig-default-configuration-check-enhancement.md
This is a proposal to check the default configuration of `KubeletConfig`
> Added KubeletConfig default configuration checks proposal

- Makefile
Signed-off-by: Matt Rogers <mrogers@redhat.com>
> Makefile: fix catalog img variable

- .github/workflows/container-scan-trivy.yml
- go.mod
- go.sum
- vendor/github.com/emicklei/go-restful/.travis.yml
- vendor/github.com/emicklei/go-restful/CHANGES.md
- vendor/github.com/emicklei/go-restful/Makefile
- vendor/github.com/emicklei/go-restful/README.md
- vendor/github.com/emicklei/go-restful/container.go
- vendor/github.com/emicklei/go-restful/cors_filter.go
- vendor/github.com/emicklei/go-restful/jsr311.go
- vendor/github.com/emicklei/go-restful/parameter.go
- vendor/github.com/emicklei/go-restful/path_processor.go
- vendor/github.com/emicklei/go-restful/request.go
- vendor/github.com/emicklei/go-restful/response.go
- vendor/github.com/emicklei/go-restful/route.go
- vendor/github.com/emicklei/go-restful/route_builder.go
- vendor/github.com/emicklei/go-restful/route_reader.go
- vendor/github.com/emicklei/go-restful/service_error.go
- vendor/github.com/emicklei/go-restful/web_service.go
- vendor/modules.txt
This adds a workflow that runs Trivy [1] on all Dockerfiles in the repository.
[1] https://aquasecurity.github.io/trivy/
> Add container and repository security scanning

- CHANGELOG.md
- doc/usage.md
Add upstream doc for `KubeletConfig` usage
> Add upstream doc for KubeletConfig usage

- Makefile
During release, tag the images built for the release version as `latest`. This ensures that the `latest` tag for all images in quay are pushed and match with the release version.
@jhrozek @rhmdnd
> Makefile: Push latest tag for all release images

- bundle/manifests/compliance-operator.clusterserviceversion.yaml
- config/manifests/bases/compliance-operator.clusterserviceversion.yaml
- config/samples/compliance.openshift.io_v1alpha1_compliancesuite_cr.yaml
- config/samples/compliance.openshift.io_v1alpha1_profilebundle_cr.yaml
Update the CSV references to the correct ghcr.io content image. Also run `make bundle` to include the update in the current bundle.
> Update content image in bundle samples

- CHANGELOG.md
- doc/usage.md
Add  remediation to compliance remediation section in the usage doc.
> Update usage doc

- cmd/manager/operator.go
Check against changing the Service's clusterIP, and retain the existing value as OCP 4.6 does not tolerate that. Later versions just ignore the field.
> Fix deployment on OCP 4.6

- CHANGELOG.md
- pkg/controller/compliancesuite/suitererunner.go
- tests/e2e/helpers.go
Let's stop using deprecated interfaces.
Resolves: rhbz#2098581
> bug 2098581: Don't import batchv1beta1 anymore

- Makefile
This commit applies some conventions to the targets and documentation
in the release section. Mostly documenting all the tools we use to
perform releases.
> Update Release section in Makefile

- CHANGELOG.md
We made some minor improvements to the Makefile. Let's signal those
changes, even if it only impacts developers.
> Update change log to include Makefile updates

- CHANGELOG.md
> changelog: Fix bug link

- tests/e2e/framework/main_entry.go
There were a couple minor comments that needed to get addressed, but
wasn't worth holding up the PR.
> Fix trivial nits from PR 250

- .github/workflows/must-gather-latest.yml
- .github/workflows/test-broken-content-latest.yml
Added two workflows to build test content image and must gather image on file changes.
> Add workflow for test content and must gather

- .github/workflows/test-broken-content-latest.yml
- images/testcontent/broken-content.sh
This pr is to fix the workflow for building test_broken_content github action.
> Fix test_broken_content github action

- CHANGELOG.md
- Makefile
- cmd/manager/operator.go
- config/generic/kustomization.yaml
- config/generic/manager_patch.yaml
- config/hypershift/kustomization.yaml
- config/hypershift/manager_patch.yaml
- config/manager/deployment.yaml
- config/openshift/kustomization.yaml
- config/openshift/manager_patch.yaml
Update Kustomize and make target to be able to deploy on generic Kubernetes cluster.
run `PLATFORM=generic make deploy-local` to deploy on a generic Kubernetes cluster
> Add an option to deploy on generic kube

- CHANGELOG.md
- pkg/profileparser/profileparser.go
- pkg/utils/parse_arf_result.go
- pkg/utils/parse_arf_result_test.go
Fix values used rendering issues for some rules. We were not checking values used in the rule's instruction, this PR checks values used in the instruction, and fix this issue.
[OCPBUGS-7456](https://issues.redhat.com/browse/OCPBUGS-7456)
> OCPBUGS-7456 Fix valuesUsed rendering

- tests/e2e/serial/main_test.go
This patches fix kubeletconfig e2e test
> Fix kubeletconfig e2e test

- config/catalog/catalog-source.yaml
- doc/tutorials/workshop/content/exercises/02-installation.md
- doc/tutorials/workshop/content/exercises/03-creating-your-first-scan.md
- doc/tutorials/workshop/content/exercises/04-remediations.md
- doc/tutorials/workshop/content/exercises/07-content-setup.md
- doc/tutorials/workshop/content/exercises/09-writing-rules.md
- Let's use resources from ComplianceAsCode/compliance-operator
- Fix typoes
- Update link to upstream operator image
- Update links to CaC/content documenation
- Update output of build_ds_container.py
> Update Workshop instructions and outputs

- doc/tutorials/workshop/content/exercises/09-writing-rules.md
- doc/tutorials/workshop/content/exercises/10-rule-parametrization.md
- doc/tutorials/workshop/content/exercises/11-node-rules.md
- doc/tutorials/workshop/content/exercises/12-common-rules.md
Add a new Workshop sections about
- Parametrizing rules with variable
- Difference between platform and node rules
- Common types of rules and their templates
> Workshop: Add new section for common rules 

- Dockerfile.ci
- Dockerfile.ocp
Let's use an image that contains a patched version of net/http.
https://github.com/golang/go/issues/63426
> Use golang 1.20

- enhancements/profile-name-in-rule.md
This PR adds the enhancement doc for adding profile names to each rules.
> [Enhancements]: Add Profile Name in Rule

- doc/tutorials/workshop/content/exercises/02-installation.md
- doc/tutorials/workshop/content/exercises/11-node-rules.md
- doc/tutorials/workshop/content/exercises/13-complex-yaml.md
- Fix the path of the subscription yaml
- Fix the command used to create node rules
- Fix command that patches an incompliant nested yaml
> Minor workshop fixes

- enhancements/profile-versioning.md
This commit adds a proposal for versioning profiles, which has been a
common ask from users.
> Propose enhancement for versioning profiles

- doc/tutorials/workshop/content/exercises/03-creating-your-first-scan.md
- doc/tutorials/workshop/content/exercises/06-troubleshooting.md
The old link was pointing to a fork which was 192 commits behind the original repo.
> update link to oc compliance plugin

- pkg/apis/compliance/v1alpha1/rule_types.go
- pkg/profileparser/profileparser.go
- pkg/utils/parse_arf_result.go
- tests/e2e/framework/common.go
- tests/e2e/parallel/main_test.go
This PR adds profile name as an annotation to each rule during parsing.
> Add Profile Name to rule

- pkg/controller/compliancesuite/suitererunner_cron_compat.go
This commit should fix the bug I noticed: https://issues.redhat.com/browse/COMPLY-1339
> [COMPLY-1339] add compare if image equals

- .github/workflows/release-pr.yml
This triggers action to run on every new PR created
> Add GitHub action to build image on new PR

- pkg/utils/remediation_diff.go
Fix a small typo, first contribution.
> Fix a small typo

- .github/workflows/release-latest.yml
- .github/workflows/release-pr.yml
- .github/workflows/release.yml
Adding s390x and ppc64le to the platform for building operator images.
Fix pr image build issues.
> Support Building multi-arch container imagers

- .github/workflows/release-latest.yml
- .github/workflows/release-pr.yml
Wait for other image builds finishes before building catalog image.
> Fix catalog image workflow

- .github/workflows/must-gather-latest.yml
- .github/workflows/test-broken-content-latest.yml
Let's fix the action for must gather, and add multi arch build to it.
> Update must gather image workflow

- images/must-gather/Dockerfile.ocp
- utils/must-gather/fetch-raw-results-pod-template.yaml
- utils/must-gather/gather_compliance
The raw-results are very helpful when debugging issues in individual rules.
> Gather scan raw-results in must-gather image

- OWNERS
This gives yuumasato the ability to apply the approved label to PRs in
this repository.
> Add yuumasato to owners file

- Makefile
We were not replacing openscap image reference in the csv bundle, this pr fixs that.
> Fix make bundle target

- bundle/manifests/compliance.openshift.io_compliancecheckresults.yaml
- bundle/manifests/compliance.openshift.io_complianceremediations.yaml
- bundle/manifests/compliance.openshift.io_compliancescans.yaml
- bundle/manifests/compliance.openshift.io_compliancesuites.yaml
- bundle/manifests/compliance.openshift.io_profilebundles.yaml
- bundle/manifests/compliance.openshift.io_profiles.yaml
- bundle/manifests/compliance.openshift.io_rules.yaml
- bundle/manifests/compliance.openshift.io_scansettingbindings.yaml
- bundle/manifests/compliance.openshift.io_scansettings.yaml
- bundle/manifests/compliance.openshift.io_tailoredprofiles.yaml
- bundle/manifests/compliance.openshift.io_variables.yaml
- config/crd/bases/compliance.openshift.io_compliancecheckresults.yaml
- config/crd/bases/compliance.openshift.io_complianceremediations.yaml
- config/crd/bases/compliance.openshift.io_compliancescans.yaml
- config/crd/bases/compliance.openshift.io_compliancesuites.yaml
- config/crd/bases/compliance.openshift.io_profilebundles.yaml
- config/crd/bases/compliance.openshift.io_profiles.yaml
- config/crd/bases/compliance.openshift.io_rules.yaml
- config/crd/bases/compliance.openshift.io_scansettingbindings.yaml
- config/crd/bases/compliance.openshift.io_scansettings.yaml
- config/crd/bases/compliance.openshift.io_tailoredprofiles.yaml
- config/crd/bases/compliance.openshift.io_variables.yaml
This is to fix failures in the `verify-bundle` workflow.
> Update bundle files

- Makefile
fix: makefile had an incorrect phony
> fix: makefile had an incorrect phony

- images/must-gather/Containerfile
- images/openscap/Containerfile
- images/operator/Dockerfile
Add labels required when shipping via Konflux
> CMP-3340: Add required labels for release

- bundle-hack/update_csv.go
Update konfluxContentPullSpec to new SHA for compliance-operator-content
> Update konflux ContentPullSpec
