CHANGELOG.md

This commit applies some consistent formatting between the release
notes and updates links to additional resources for readers. Proposing
this ahead of the v0.1.50 release so there is less churn in the release
patch.

Prepare release notes for release v0.1.50

---

CHANGELOG.md
pkg/controller/compliancescan/scan.go

Fix OpenScap scanner container crashloop caused by script mount permission issue on a security envronment where DAC_OVERRIDE capability is dropped. This PR chanes script mount permission to give excute permission to all users. [bug](https://bugzilla.redhat.com/show_bug.cgi?id=2082151) for more information.

Bug 2082151: Fix scanner pod script mount permission

---

CHANGELOG.md
cmd/manager/aggregator.go
deploy/compliance-operator-chart/crds/compliance.openshift.io_tailoredprofiles_crd.yaml
deploy/crds/compliance.openshift.io_tailoredprofiles_crd.yaml
deploy/role.yaml
doc/crds.md
pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
pkg/apis/compliance/v1alpha1/tailoredprofile_types.go
pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
pkg/controller/tailoredprofile/tailoredprofile_controller.go
pkg/controller/tailoredprofile/tailoredprofile_controller_test.go
pkg/profileparser/profileparser_suite_test.go
pkg/utils/nameutils.go
pkg/utils/parse_arf_result.go
pkg/utils/parse_arf_result_test.go
pkg/xccdf/tailoring.go
tests/e2e/e2e_test.go

This PR enables users to disable automated checks on rules so that they can check those rules manually. They can do that by adding rules under manualRules in TailoredProfile Spec.
ex.
```
kind: TailoredProfile
metadata:
name: mod-node
spec:
title: My modified profile with manual rules
manualRules:
- name: ocp4-kubelet-eviction-thresholds-set-soft-imagefs-available
rationale: test
description: test
```

Add manualRules to tailoredProfile CRD

---

.github/workflows/release-latest.yml
.github/workflows/release.yml

This adds two jobs:
* One that with every push to the `master` branch, will build and
publish the compliance-operator container to the `latest` tag.
* Another one that with every release tag (e.g. `v0.1.51`), will build
and publish to that specific tag.
Both of these jobs publish the container images to the GitHub container
registry (`ghcr.io`), do container signing via sigstore and generate
provenance information.

Add container release jobs

---

Makefile

We've been building Kubernetes content in a [GitHub Action](https://github.com/ComplianceAsCode/content/blob/master/.github/workflows/k8s-content.yaml)
for a while now; let's take that into use!
This now uses `ghcr.io/complianceascode/k8scontent:latest` which allows
us to fetch the latest content from ComplianceAsCode/content and is also
signed.
Signed-off-by: Juan Antonio Osorio <juan.osoriorobles@eu.equinix.com>

Use content image from GHCR

---

CHANGELOG.md

This commit removes unpopulated sections of the change log, uses
literals where appropriate, and clarifies what users need to do, if
anything, to consume the updates in the new version of the compliance
operator.

Fix up release notes for 0.1.53

---

CHANGELOG.md

Historically, we've only been including CO fixes in CO's changelog. This
was, while technically correct, confusing to users, who tend to consume
the operator and the content as a single unit.
Let's mention the important content fixes and improvements in a
sub-section of the CHANGELOG.md file to better inform our users about
what's new.

changelog: Point out important fixes to OCP4/RHCOS4 compliance content

---

.github/workflows/release.yml

This CI is failing because the Dockerfile is not available:
unable to prepare context: unable to evaluate symlinks in Dockerfile
path: lstat
/home/runner/work/compliance-operator/compliance-operator/Dockerfile:
no such file or directory
This commit attempts to fix the issue by using the correct dockerfile
path.

Fix the dockerfile path in the release CI

---

CHANGELOG.md
enhancements/README.md
enhancements/template.md

This commit adds a template (originally proposed in
https://github.com/ComplianceAsCode/compliance-operator/pull/2) to the
compliance-operator repository.
Adding this in its own PR so we can merge it an use it for other
enhancements while we iterate on the results forwarding enhancement.

Add an enhancements template

---

pkg/utils/nodeutils.go
pkg/utils/nodeutils_test.go

It is possible that KubeletConfigs will render more than just a single file in the generated MachineConfig objects. Currently the Compliance Operator is hardcoded to select the first file expecting it to be the `kubelet.conf` file. This is _not_ always the case.
This change uses a jsonpath filter to select the desired `/etc/kubernetes/kubelet.conf` file's contents. Fixes #60 
For example, when setting `autoSizingReserved: true` in a KubeletConfig, it will generate a MachineConfig like this:
```
spec:
config:
ignition:
version: 3.2.0
storage:
files:
- contents:
source: data:text/plain,NODE_SIZING_ENABLED%3Dtrue%0ASYSTEM_RESERVED_MEMORY%3D1Gi%0ASYSTEM_RESERVED_CPU%3D500m%0A
mode: 420
overwrite: true
path: /etc/node-sizing-enabled.env
- contents:
source: data:text/plain,TRUNCATED
mode: 420 …
```

BUG 2102511: Fix hardcoded logic by filtering to expected file name.

---

cmd/manager/operator.go
cmd/manager/operator_test.go
tests/e2e/e2e_test.go

Take the given operator namespace into account when setting the
ServiceMonitor ServerName field. Previously it was always assumed to be
openshift-compliance.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=2060726

Bug 2060726: Use namespace when creating ServiceMonitor

---

CHANGELOG.md
cmd/manager/scap.go
cmd/manager/scap_test.go

While filtering files out of MachineConfigs, we tried to also parse
ignition specification of MachineConfigs that didn't specify any,
leading to an error.
Let's just pass on MCs that don't have any Ignition spec as-is.
Resolves: rhbz#2117268

Bug 2117268: api-resource-collector: Don't attempt to parse empty Ignition

---

CHANGELOG.md
cmd/manager/operator.go
pkg/controller/common/constants.go

It was reported that using WATCH_NAMESPACE=openshift-compliance (or
installing into its own namespace) reduced memory usage of the operator:
https://github.com/ComplianceAsCode/compliance-operator/issues/40#issuecomment-1155180160
Let's implement Matt's suggestion from that issue and override the value
of WATCH_NAMESPACE.
Fixes: #40

operator: Override WATCH_NAMESPACE="" to WATCH_NAMESPACE=openshift-compliance

---

.gitignore

The operator-sdk update refactored how we setup end-to-end testing. Part
of that was to include a separate directory for custom resource
defintions and custom resources generated by the tooling.
Since the files in tests/_setup are generated, we don't need to track
them in the project. Let's add them to .gitignore.

Ignore tests/_setup directory

---

CHANGELOG.md
Makefile

We don't always know what repository the origin remote is pointing to,
but the release process expects it to be the upstream repository.
Let's make sure that's what we're pushing release information to.
Fixes #8

Use an absolute reference for the release remote

---

CHANGELOG.md

Even though this is an internal change, and shouldn't really impact end
users at all, we should add a release note for it to advertise some of
the benefits.

Add a release note for Operator SDK bump

---

images/openscap/Dockerfile
images/openscap/Dockerfile.ci

This repo is no longer needed as the base UBI-8 repos have even newer
openscap image (1.3.6) than what the repo has.

images: Don't enable an obsolete copr repo

---

Makefile
bundle/manifests/compliance-operator.clusterserviceversion.yaml
config/manager/deployment.yaml

Previously we switched the content images to default to
`ghcr.io/complianceascode/k8scontent:latest`, and this was reverted on
accident in the operator-sdk upgrade patch.

Use ghcr.io content image as default

---

CHANGELOG.md
pkg/controller/compliancescan/compliancescan_controller.go
pkg/controller/compliancescan/compliancescan_controller_test.go

When scansetting was set with debug:true and the scan was deleted, the
scan pods stayed around even if the scan was deleted.
rhbz: #2092913

bug 2092913: scan: Delete scan pods when deleting the scan itself and debug: true

---

Makefile

The `make e2e-cluster` target runs the e2e suite against the images that are pushed to the local cluster with `image-to-cluster`. During `image-to-cluster` we also need to set IMG to the operator. This allows kustomize to set the image reference properly when the `e2e-set-image` prereq is called.

Makefile: Set IMG during image-to-cluster

---

Makefile
tests/e2e/framework/context.go
tests/e2e/framework/framework.go
tests/e2e/helpers.go

This introduces the `E2E_TEST_TYPE` variable, which, if set, allows the
e2e test suite to run only a subset of tests. This subsets are defined
in-code and currently only take either `parallel` or `serial`. However,
the default is to run them all (the default is literally called `all`)
so the current behavior is kept.
This will allow us to create another test in the `openshift/release`
repo and divide the test runs to take different clusters, which will
speed up the e2e CI run.
We could have `e2e-serial` and `e2e-parallel` tests.
Signed-off-by: Juan Antonio Osorio <juan.osoriorobles@eu.equinix.com>

Allow running a subset of tests through a MakeFile variable

---

Makefile
doc/contributor.md

- The correct target to create and push the index is `catalog`, so use that for `release-images`
- Correct the use of VERSION, and add a note about unsetting IMAGE_REPO and TAG prior to release in to doc/contributor.md
Signed-off-by: Matt Rogers <mrogers@redhat.com>

Makefile: Fix release-images target prereqs

---

tests/e2e/framework/framework.go

The value passed in to the test binary was being lost on the way. This caused the e2e to skip all tests by default.
Signed-off-by: Matt Rogers <mrogers@redhat.com>

Fix -testType option for e2e

---

Makefile

By setting the `-trimpath` flag, we ensure that we don't pollute the
debug paths with absolute paths of the environment where we built the
image; instead, this will will show the path of the go module (which is
also quite understandable for debugging). Making the go binary's buildid
blank also ensures that the binary has data we can predict, and thus
ensures reproducible builds.
Signed-off-by: Juan Antonio Osorio <juan.osoriorobles@eu.equinix.com>

Reproducible builds: Ensure we can get reproducible builds for CO

---

Dockerfile.ci
Dockerfile.ocp
build/Dockerfile
go.mod
go.sum

This upgrades the container images to use golang 1.18 and executes a
`go mod tidy -compat=1.18`.
Signed-off-by: Juan Antonio Osorio <juan.osoriorobles@eu.equinix.com>

Update to golang 1.18

---

CHANGELOG.md
config/crd/bases/compliance.openshift.io_compliancescans.yaml
config/crd/bases/compliance.openshift.io_compliancesuites.yaml
config/crd/bases/compliance.openshift.io_scansettings.yaml
config/helm/crds/compliance.openshift.io_compliancescans_crd.yaml
config/helm/crds/compliance.openshift.io_compliancesuites_crd.yaml
config/helm/crds/compliance.openshift.io_scansettings_crd.yaml
doc/crds.md
pkg/apis/compliance/v1alpha1/compliancescan_types.go
pkg/apis/compliance/v1alpha1/zz_generated.deepcopy.go
pkg/controller/compliancescan/scan.go
tests/e2e/e2e_test.go
tests/e2e/helpers.go

Even with the recent fix to the memory consumption, we might need to
provide a way for our users to bump the limits on scans, especially with
huge cluster nodes and Linux scans that traverse the filesystem.
This patch adds a new scanLimits attribute to the scan settings CR.
If unset, the compiled-in defaults are used, otherwise the settings take
precedence.
The only containers that are affected are the scanner and the
api-resource-collector as we've seen reports with those containers being
OOMKilled.
Jira: OCPBUGSM-39585

Make scanner's and api-resource-collector's limits configurable

---

cmd/manager/resultserver_test.go

The last resultserver unit test (rotation of 3 directories with policy=2) often failed on ppc64le systems. It was observed that test directories created only within 5 milliseconds of each other could result in an identical creation time, and affect the expected results.
This increases the delay between test directories to 100ms to better ensure a different creation time on ppc64le.

Resultserver rotation test timing

---

CHANGELOG.md

This commit was supposed to get released in 0.1.54, but it missed the date. This commit pulls the release note from 0.1.54 and puts it in 0.1.55 so that we don't mislead readers.

Move limit release note to correct release.

---

Makefile

Bumps the kustomize tool version to v4 to accommodate go1.18, and use `go install`.

Makefile: Fix kustomize install for go1.18

---

CHANGELOG.md
Makefile
utils/git-remote.sh

Our upstream release process expects maintainers to propose release patches, branches, and tags to the upstream repository (ComplianceAsCode/compliance-operator). Some people prefer to setup their upstream remote as origin, while others use upstream.
This change introduces a script to determine which git remote to use for the GIT_REMOTE variable based on the url associated with the upstream repository. This makes the release process consistent, regardless of who is doing the release. This commit also removes an extra GIT_REMOTE defintion in the Makefile, making it clear where we're setting that variable and what the intended value should be.

Add a script to conditionally set upstream remote

---

cmd/manager/operator.go
cmd/manager/operator_test.go

Rather than the defaulted epoch time, change the zap logger settings to provide a human readable timestamp, e.g.,
{"level":"info","ts":"2022-09-27T20:22:40.161Z","logger":...

Use ISO 8601 time format for logs

---

CHANGELOG.md
pkg/controller/compliancesuite/compliancesuite_controller.go
pkg/controller/compliancesuite/suitererunner.go
pkg/controller/compliancesuite/suitererunner_cron_compat.go

We removed the usage of v1beta1 cronjob API in
5c860d72a438ce5769cead38a7faa3fef089be3d but now that came back to bite
us since on older OpenShift versions (4.6 and 4.7) the beta API is the
only one available.
Let's try to use the v1 API and fall back to the beta API if needed.
Resolves: OCPBUGS-2156

OCPBUGS-2156: suite: Fall back to using betav1 cronjob if v1 cronjob is not available

---

Makefile

The Generate section of the Makefile wasn't rendered properly when
running `make help`. This commit removed a redundant, empty section and
documents two additional targets in that section so they're output when
you run `make help`.

Fix Makefile Generate section

---

Makefile

Some of our targets have long names. Mixing long and short targets
causes the help text for each to be formatted inconsistently.
This commit updates the help text to supply description after a tab,
which should keep the indentation consistent.

Use tab indentation for `make help`

---

.gitignore
Makefile

Saving these logs are helpful. Let's tee stdout to a file we can use
later.

Stash e2e test output when running locally

---

images/openscap/Dockerfile

RH has fixed CVE-2022-3515 already in an update, but the UBI update lags
behind. Upgrade the package manually in the meantime.

openscap: Update libksba manually to make CVE scanners happy

---

images/openscap/Dockerfile

This reverts commit 147d8c3873950068d880abd93ce8ba3d399bd874 which
should no longer be needed becuse the UBI image was refreshed.

Revert "openscap: Update libksba manually to make CVE scanners happy"

---

CHANGELOG.md
cmd/manager/operator.go

* The metrics port configuration was being set to a default of 8080 due to an unused options setup variable, this is corrected to be hard-coded to 8383.
* Pass namespace to the controller manager on startup, which now allows the WATCH_NAMESPACE adjustments to take place. The operator pod will now only watch in the operator namespace, reducing memory usage when there are many namespaces.
Fixes: https://issues.redhat.com/browse/OCPBUGS-3097

OCPBUGS-3097: Metrics and watch namespace fixes

---

CHANGELOG.md
Makefile

We need to keep track of the version number in preamble.json for the
operator index image.
Let's make sure we add it to the makefile targets for releasing the
operator so that it's included in the release commit.

Add preamble.json to release targets

---

CHANGELOG.md
bundle/manifests/compliance.openshift.io_scansettingbindings.yaml
config/crd/bases/compliance.openshift.io_scansettingbindings.yaml
pkg/apis/compliance/v1alpha1/scansettingbinding_types.go
tests/e2e/e2e_test.go

By default, ScanSettingBindings don't need to reference a ScanSetting
using the SettingsRef. If you create a binding without a reference to a
scan setting, the scan will run anyway but doesn't take on any of the
default behaviors of the `default` ScanSetting.
This commit fixes this behavior by updating the default for the
ScanSettingBinding settingRef to the `default` ScanSetting.
Related Jira: https://issues.redhat.com/browse/OCPBUGS-3420

OCPBUGS-3420: Ensure ScanSettingBindings use the default ScanSetting by default

---

CHANGELOG.md
config/crd/bases/compliance.openshift.io_compliancecheckresults.yaml
pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
pkg/utils/parse_arf_result.go
pkg/utils/parse_arf_result_test.go

Fixes an [issue](https://issues.redhat.com/browse/OCPBUGS-4615) where `ComplianceCheckResult` objects do not have correct descriptions, we corrected the descriptions, and also added a new `rationale` field to `ComplianceCheckResult` objects.

OCPBUGS-4615: Correct rule description

---

CHANGELOG.md
pkg/apis/compliance/v1alpha1/scansettingbinding_types.go
pkg/controller/scansettingbinding/scansettingbinding_controller.go
pkg/controller/scansettingbinding/scansettingbinding_controller_test.go
tests/e2e/e2e_test.go

Since we switched to the new way of remediating kubeletConfigs, setups
that use a non-default pool name require that the pool is set in
variables in a tailored profile. Otherwise, some remediations might be
set cluster-wide which can cause issues, e.g. if the platform-level remediation that
sets protectKernelDefaults is set cluster-wide, but the node level
remediation that sets the required sysctls is only set pool-wide.
Protect the user againts shooting themselves in the foot by refusing to
process this kind of SSB CRs.
Resolves: OCPBUGS-3864

OCPBUGS-3864: ssb: Error if attempting to use a non-default pool but the pool variables are not set

---

tests/e2e/e2e_test.go

This PR is to fix TestKubeletConfigRemediation e2e test

Fix e2e test

---

CHANGELOG.md
pkg/profileparser/profileparser.go
pkg/utils/parse_arf_result.go
pkg/utils/parse_arf_result_test.go

This is in addition to https://github.com/ComplianceAsCode/compliance-operator/pull/191.
This adds variable rendering in instructions.

OCPBUGS-4615: Fix rendering variables in instructions

---

CHANGELOG.md
pkg/utils/compare_json.go
pkg/utils/nodeutils.go
pkg/utils/nodeutils_test.go

Added check for nil pointer before comparing if KubeletConfig is fully rendered。
This is necessary because setting the KubeletConfig object incorrectly can result
in an empty KubeletConfig Spec, which can cause a panic error. This check will prevent
this issue and ensure the comparison is performed safely.
[OCPBUGS-4621](https://issues.redhat.com/browse/OCPBUGS-4621)
Example of an incorrect way of setting autoSizingReserved KubletConfig:
```
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
name: dynamic-node
spec:
autoSizingReserved: true
machineConfigPoolSelector:
matchLabels:
pools.operator.machineconfiguration.openshift.io/worker: ""
```
Instead, it should be set as follows according to [OpenShift …

OCPBUGS-4621: Add non-nil check before comparing if KubeletConfig is fully rendered

---

CHANGELOG.md
pkg/utils/nodeutils.go
pkg/utils/nodeutils_test.go

System reserved parameters do not get generated into `/etc/kubernetes/kubelet.conf`, and it is causing Compliance Operator to fail to unpause the machine config pool, this PR excludes node sizing, and system reserved parameters from checking if KubeletConfig is not part of the generated Machine Config since it does not get generated into `/etc/kubernetes/kubelet.conf` file.
[OCPBUGS-4445] https://issues.redhat.com/browse/OCPBUGS-4445
See the slack thread for more details: https://coreos.slack.com/archives/C02CZNQHGN8/p1669843411934799?thread_ts=1669842906.487409&cid=C02CZNQHGN8

OCPBUGS-4445: Excludes node sizing, and system reserved parameters from KubeletConfig rendering checks

---

CHANGELOG.md
pkg/controller/complianceremediation/complianceremediation_controller.go
pkg/controller/complianceremediation/complianceremediation_controller_test.go

Make Compliance Operator apply all the related remediations for one ComplianceCheckResult at once, this helps users who use manual remediation, this feature will look for all the related remediations for a ComplianceCheckResult when one remediation is applied.
For ex. we have 
```
ocp4-cis-kubelet-eviction-thresholds-set-soft-nodefs-inodesfree                                  
ocp4-cis-kubelet-eviction-thresholds-set-soft-nodefs-inodesfree-1                              
ocp4-cis-kubelet-eviction-thresholds-set-soft-nodefs-inodesfree-2         
ocp4-cis-kubelet-eviction-thresholds-set-soft-nodefs-inodesfree-3     
ocp4-cis-kubelet-eviction-thresholds-set-soft-nodefs-inodesfree-4
```
remediations, when a user applies either one of them, we will apply all the other remediations associated …

OCPBUGS-4338: Apply all remediations associate with each ComplianceCheckResult

---

CHANGELOG.md
config/crd/bases/compliance.openshift.io_compliancescans.yaml
config/crd/bases/compliance.openshift.io_compliancesuites.yaml
config/crd/bases/compliance.openshift.io_scansettings.yaml
doc/usage.md
pkg/apis/compliance/v1alpha1/compliancescan_types.go
pkg/apis/compliance/v1alpha1/conditions.go
pkg/controller/common/errors.go
pkg/controller/compliancescan/aggregator.go
pkg/controller/compliancescan/compliancescan_controller.go
pkg/controller/compliancescan/scantype.go
tests/e2e/e2e_test.go

The scan now has a timeout option that can be specified in the `ComplianceScanSettings `object as a duration string (e.g. 1h30m). If the scan does not finish within the specified timeout, it will either be reattempted (up to a maximum of `MaxRetryOnTimeout` times) or considered a failure, depending on the value of `MaxRetryOnTimeout`. The timeout can be disabled by setting it to 0s, and the default value is 30m. The default value for `MaxRetryOnTimeout` is 3, so the timeout scan will be retried up to three times if it fails.
To set a `Timeout` and `MaxRetryOnTimeout` in ScanSetting:
```
kind: ScanSetting
metadata:
name: default
namespace: openshift-compliance
rawResultStorage:
rotation: 3
size: 1Gi
roles:
- worker
- master
scanTolerations:
- …
```

Add Timeout for scanner pod

---

tests/e2e/helpers.go

This PR adds a 5-second wait after we found the remediation, this helps remediation gets applied before we check MCP updates.

Fix e2e flaky issue

---

enhancements/results-forwarding.md

This commit writes down the proposal for implementing a results
forwarding mechanism in the compliance operator.
Co-Authored-By: Juan Antonio Osorio juan.osoriorobles@eu.equinix.com

Add enhancement proposal for result forwarding

---

config/rbac/operator_cluster_role.yaml

- CO ClusterRole: Add the permissions to operate on templates.template.openshift.io
- CO ClusterRole: Add the permissions to operator on projects.config.openshift.io
I'm working on checks and remediations that set up cluster config and projects template so that
all newly created projects include a NetworkPolicy. These RBAC rules are needed in order to create the corresponding remediations.

Update RBAC to allow remediations that set projects templates

---

CHANGELOG.md
pkg/apis/compliance/v1alpha1/complianceremediation_types.go
pkg/apis/compliance/v1alpha1/complianceremediation_types_test.go
tests/e2e/e2e_test.go

Because the remediation contents we Get() from the cluster after they've
been applied contain an empty Annotations map, but the remediations we
parse from content do not, the comparison always yielded false and the
remediatins have been set to Outdated as a result.
This patch adds an empty annotations map to remediations before
comparing them, so that we compare their normalized version.
note: I have not ran the e2e test addition yet. I did test the PR manually, though.

OCPBUGS-6710: remediations: Normalize remediations' annotations to avoid needlesly marking remediations as Outdated

---

pkg/apis/compliance/v1alpha1/complianceremediation_types.go
pkg/apis/compliance/v1alpha1/complianceremediation_types_test.go

Two simple patches
- complianceremediation api: remove unused method
- tests: Improve tests to normalize compliance remediations

Minor follow-ups to code review of PR 206

---

CHANGELOG.md
pkg/controller/scansettingbinding/scansettingbinding_controller.go
tests/e2e/e2e_test.go

Xiaojie noticed an issue in my previous PR to check for non-default roles, but I didn't have time to address
her feedback before the PR was merged.
Opening this PR as a way to track the comments. I'm not 100% sure that the PR is correct, so please treat as a WIP for now.

OCPBUGS-6827: ssb: Presume Platform scan if no scan type is given with annotations

---

cmd/manager/resultcollector.go

Directly calling os.Exit means that we don't even log which file failed
to open which makes triaging issues harder.

cleanup: Don't return from a utility function, return an error instead

---

Makefile
doc/contributor.md

While end-to-end coverage is important, it's good to have an idea of
what parts of the code aren't being exercised with unit tests. Good unit
tests can provide efficent coverage without expensive infrastructure or
wait times.
This commit makes it easier for developers to see test coverage by
adding an explicity target for it.

Add Makefile target for generating unit test coverage reports

---

Makefile

Without a comment in the target, the target isn't rendered when you use
`make help`. The e2e target is useful for contributors. Let's make sure
it shows up in `make help`.

Add e2e help text to Makefile

---

Makefile
doc/contributor.md

The Makefile referenced an old example of how to run a single test that
was inaccurate and outdated.
Let's update it so that it's easier to understand how to invoke a single
e2e test.
Fixes #226

Update e2e examples for running a single test

---

renovate.json

There has been a lot of dependency churn lately which is congesting CI,
costing money and making it hard to follow all PRs. Let's update
dependencies weekly only.
In addition, let's set the labels that allow CI to be run automatically
and ensure that the `{px,docs,qe}-approved` labels are set on the PRs so
that we don't have to do that ourselves.

renovate: Open PRs on weekends only, set labels

---

tests/e2e/framework/context.go

We've noticed that some of the tests aren't cleaning up the way we
expect. Specifically, some of the compliance scans are still laying
around even when we exit the context Cleanup() function, which is
designed to execute a bunch of callbacks to cleanup test resources.
This probably isn't much of a problem in CI since the cluster gets torn
down after the tests run, but it impacts contributor's ability to re-use
the same environment for multiple e2e runs. Ideally, we want to run a
single test in isolation and have it cleanup after itself so we can
continue using the same environment.
This commit adds basic logging in Cleanup() that logs how many scans are
left over before we tear down the environment.

Add cleanup logging after tests run

---

Makefile

The e2e test framework keeps track of tests that are safe to run
concurrently and which must be run serially.
For example, tests that focus on scanning and don't interfere with each
other are safe to run in parallel. Tests that apply remediations to the
cluster impact other tests that assert specific checks or outcomes from
a scan.
We typically lump all these tests into a single run using `make e2e` and
ensure the concurrent tests are run first, followed by the serial tests.
By adding separate makefile targets, we're making it easier for
contributors to run a group of tests, instead of the whole suite,
shortening the feedback loop. We can also use this in CI and create
separate jobs, running parallel tests and serial tests on different
clusters, speeding up CI reporting time. It's also …

Add makefile targets to run serials and parallel e2e tests

---

tests/e2e/helpers.go

Simplfy error construction using fmt.Errorf, based on
https://staticcheck.io/docs/checks#S1028

Use fmt.Errorf instead of errors.New

---

cmd/manager/resultcollector.go
cmd/manager/resultcollector_test.go
cmd/manager/resultserver.go
cmd/manager/resultserver_test.go
cmd/manager/scap.go
cmd/manager/scap_test.go
pkg/controller/common/constants.go
pkg/utils/resultconfigmap.go
tests/e2e/framework/framework.go
tests/e2e/framework/projutil.go
tests/e2e/framework/resource.go
tests/e2e/helpers.go

The ioutils module was deprecated in 1.19 and its functionality
replaced with io and os modules.
https://pkg.go.dev/io/ioutil
Let's use those instead.

Replace ioutils with io and os modules

---

Makefile

We recently separated e2e in to two distinct targets so it was easier to
run them as two different CI jobs. But, we used the wrong argument.
This commit uses the right argument to select the parallel or serial
tests.

Use correct flag for e2e-parallel and e2e-serial

---

tests/e2e/framework/client.go
tests/e2e/framework/common.go
tests/e2e/framework/context.go
tests/e2e/framework/framework.go
tests/e2e/framework/main_entry.go
tests/e2e/framework/resource.go

The e2e tests use a nested test structure, where TestE2E is the
grandparent test, TestE2E/Serial_tests and TestE2E/Parallel_tests are
the parent tests, and each test case is technically a grandchild of
TestE2E.
We use this structure so that TestE2E can actually setup shared
resources for the test (like deploying and configuring the operator).
All the setup functionality used the same .Create() method available
through the test framework client, which automatically defers cleanup of
those resources by executing the deferred calls in a FILO order (stack).
However, as we've seen in various test runs, it's possible for CRDs to
get cleaned up before all resources have been deleted. This orphans the
resources, making them harder to cleanup, leaving the operator resources
and it's namespace in a …

Refactor e2e test cleanup

---

tests/e2e/framework/context.go

That argument doesn't actually exist. Instead we have
`-skipCleanupOnError`. If you read the log and then try to use
`--skip-cleanup-error` you'll get a different error about an unsupported
argument.
This commit updates the log to output the correct argument.

Fix test log about --skip-cleanup-error

---

tests/e2e/framework/resource.go

The GetNamespace method was deprecated and we have a suitable
replacement called GetOperatorNamespace. All test code is already
updated to use the new method.
This commit removes the deprecated function so we don't have cruft
laying around.

Remove deprecated test context method

---

config/rbac/api_resource_collector_cluster_role.yaml

One of STIG compliance rules requires to read this API resource.

rbac: Allow to Read imagepruners

---

Makefile
tests/e2e/framework/context.go
tests/e2e/framework/framework.go
tests/e2e/framework/main_entry.go

The flag skipCleanupOnError defaulted to false, meaning it would cleanup
test resources in the event of a failure. In the Makefile target for e2e
tests, we override -skipCleanupOnError with true, so we keep resources
when a test fails.
Depending on if you're running the tests using `make e2e` or directly
using `go test` you'd get different behavior.
This commit renames the variable to be more affimative by removing
`skip` from the name (skipCleanupOnError actually means
cleanupOnError=false). It also converges the default in the test runner
to be the same as the default in the Makefile, allowing for consistent
behavior regardless of how you invoke the tests. It also adds more help
text to clarify the behavior.

Simplify skipCleanupOnError test flag

---

CHANGELOG.md
cmd/manager/scap.go
cmd/manager/scap_test.go
tests/data/configmap_json.json
tests/data/configmap_yaml.json

Modify API resource collector to detect and convert fetched resources to json format when they are returned in yaml format. This is required because some API resources are not available in json format and need to be converted to json format for reading by OpenSCAP.
example rules:
```
applications/openshift/api-server/ocp_api_server_audit_log_maxsize
applications/openshift/api-server/ocp_api_server_audit_log_maxbackup
```

Modify API Resource Collector to Convert YAML to JSON Format

---

tests/e2e/framework/projutil.go

This keeps getting updated in development workflows (`make build`, `make
format`). Let's just update it in a separate patch.

Fix formatting in projutil.go

---

CHANGELOG.md
doc/usage.md

Added documentation on how to run a scan on HyperShift Management Cluster

Add HyperShift usage doc

---

tests/e2e/e2e_test.go

The TestSingleTailoredPlatformScanSucceeds creates a simple tailored
profile with a single rule, binds it to a scan setting, then asserts the
scan was compliant.
This recently started failing because it was using the
scheduler_no_bind_address rule, which is not applicable to newer
versions of OpenShift:
https://github.com/ComplianceAsCode/content/commit/778fae292ca76a16b3a191b0a1f75d9241e16dd0
This resulted in the scan result coming back as not applicable instead
of compliant.
This commit uses a different rule for the tailored profile that's still
supported on newer versions of OpenShift so our CI works again.
Fixes #276

Fix TestSingleTailoredPlatformScanSucceeds by using supported rule

---

config/manifests/bases/compliance-operator.clusterserviceversion.yaml

We moved the code from openshift/compliance-operator to
ComplianceAsCode/compliance-operator, but we did't update the manifest
references. This means the bundle image would still point to the origin
repository, which isn't what we want.
We attempted to fix this in PR #230, but we only modified the bundle
manifest, which is generated from the manifest base. This commit updates
the manifest base so that it uses the correct URL, too.

Fix upstream repository URL

---

config/manifests/bases/compliance-operator.clusterserviceversion.yaml

I just patched this to fix the repository URL, but it also helps enable
spell checking tools.

Fix upstream repository URL... again

---

config/rbac/api_resource_collector_cluster_role.yaml

See the patch, it's just a trivial addition of two RBAC rules needed for the STIG

rbac: Allow reading scansettings and scansettingbindings

---

CHANGELOG.md
pkg/utils/xml2text.go
pkg/utils/xml2text_test.go

The operator uses a handy library for converting HTML-like text to
markdown. This is nice for content text that informs users about what to
do with specific findings because it's formatted (e.g., adding lines
around formatted code snippet).
Unfortunately, the parser didn't account for links, which contain
multiple XML elements. The original `<a></a>` tag was preserved but the
actual link reference in `href=example.com` was dicarded.
This results in none of the links we put in content getting rendered in
the actual CRs where users can read and use them.
This commit adds some special handling for XML start elements to detect
cases where we're dealing with links and ensures they get propogated
into the final Markdown representation.

OCPBUGS-4409: Support converting HTML links to Markdown

---

bundle/manifests/compliance-operator.clusterserviceversion.yaml

In cac/content testing, we are now using nightly operator images, which
are built after every commit to cac/compliance-operator. However,
bundle manifests are only refreshed on release, which means that some
code changes like rbac modifications are not reflected.
This causes CI failures in cac/content unless we release.

Run 'make bundle' to commit bundle manifest changes

---

CHANGELOG.md
Makefile
config/catalog/subscription-hypershift.yaml
doc/usage.md

Added Subscription file needed for deploying CO on HyperShift Hosted Cluster through OLM, it can be used from both upstream or downstream sources.

Add ability to deploy CO on Hosted Cluster through OLM

---

CHANGELOG.md
cmd/manager/api-resource-collector.go
cmd/manager/operator.go
cmd/manager/scap.go
pkg/controller/compliancescan/scan.go

Added an ability to identify which platform we are on using a CPE. We always fetch the api-checks-pod object, and save it to a dump file when API-resource collector is running, CPE can use the dump file to check the command line arguments to see if we are running on a specific platform.
We now read the PLATFORM env variable, and override the platform command set in the deployment, because env can be set by the OLM subscription file.

Fetch CO deployment object for Platform CPE

---

Makefile
config/openshift-bundle/kustomization.yaml
config/openshift-bundle/manager_patch.yaml

Commit 03ef0398dd26d85737bfdbf6fe14f37b116abbb6 removed the OCP-specific
nodeSelector and tolerations from the default deployment at
`config/manager/deployment.yaml`. This would mean that the bundle
wouldn't have them at all, which is fine for generic Kube deployments,
but we still want to have them on OCP.
This patch introduces an OCP specific bundle kustomization that applies
a patch to the manager config that patches back the nodeSelector and the
tolerations.

OLM: Provide an OCP-specific bundle kustomize

---

Makefile
doc/contributor.md

Now that we've graduated the operator to v1.0 and we have a specific
branch for that version called `ocp-1.0`, we should update those
references in the Makefile and documentation so the automation continues
to do what it should for Compliance Operator builds.

Update ocp branch references

---

cmd/manager/aggregator.go
pkg/controller/compliancescan/forwarder.go
pkg/controller/compliancescan/forwarder_test.go

This commit identifies a basic seam to implement result and remediation
forwarding. While this commit is non-functional, it serves a purpose in
debating where we put the functionality and what the interface looks
like.

Implement result and remediation forwarding

---

CHANGELOG.md
doc/usage.md
pkg/controller/compliancescan/config.go

In some cases it's handy to enable the DEVEL debug level for OpenScap,
e.g. to diagnose issues in the scanner itself.
In order to keep the semantics of the current `debug` attribute of the
scans, but still allow setting the very verbose debug level, let's
take the value of the `OSCAP_DEBUG_LEVEL` environment variable into
account.
The variable can be set either directly in the operator deployment or
through OLM Subscription.

Allow setting the OSCAP_DEBUG_LEVEL to tune OpenScap debug level

---

build/Dockerfile

If you build the Compliance Operator from source and deploy it into a
cluster using `make deploy-local`, you'll see that the operator fails to
start because of a GLIBC error:
```
compliance-operator: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by compliance-operator)
compliance-operator: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by compliance-operator)
```
This is because the container image for golang:1.20 is referencing a
newer version fo GLIBC than what's available in the ubi8 minimal image.
This commit updates the ubi image so that we keep up with the GLIBC
version being referenced in newer golang versions.
Fixes #372

Update UBI image to keep pace with GLIBC version

---

CHANGELOG.md
bundle/manifests/compliance-operator.clusterserviceversion.yaml
cmd/manager/operator.go
config/rbac/operator_cluster_role.yaml
config/rbac/operator_role.yaml
main.go
pkg/apis/compliance/v1alpha1/compliancescan_types.go
pkg/apis/compliance/v1alpha1/scansettingbinding_types.go
pkg/controller/complianceremediation/complianceremediation_controller.go
pkg/controller/compliancescan/compliancescan_controller.go
pkg/controller/compliancescan/compliancescan_controller_test.go
pkg/controller/compliancescan/config.go
pkg/controller/compliancescan/scan.go
pkg/controller/compliancescan/utils.go
pkg/controller/compliancesuite/compliancesuite_controller.go
pkg/controller/controller.go
pkg/controller/profilebundle/profilebundle_controller.go
pkg/controller/scansettingbinding/scansettingbinding_controller.go
pkg/controller/scansettingbinding/scansettingbinding_controller_test.go
pkg/controller/tailoredprofile/tailoredprofile_controller.go
vendor/k8s.io/client-go/rest/fake/fake.go
vendor/modules.txt

This PR aims to optimize how we check the `KubeletConfig` rule. Currently, to check the runtime `KubeletConfig` configuration, we fetch all nodes `KubeletConfig`, compare them, and merge them into a file per MachineConfig pool. This approach relies on the node label, which might not work on other Kubernetes distros such as EKS, we use @all on EKS. Also, if there are more than two machine config pool or their names are not master/worker, they might need a tailored profile.
To address this issue, we propose to store the runtime `KubeletConfig` in a ConfigMap per node when a node scan is launched. Then, we mount the ConfigMap to the scanner pod to scan for it.
* No need to set up role variables using a tailored profile: Currently, our approach requires setting up role variables based on the …

Optimize how we check runtime KubeletConfig

---

.github/workflows/release-latest.yml
.github/workflows/release.yml

The `release` and `release-latest` GitHub Actions are failing with `invalid` error:
https://github.com/ComplianceAsCode/compliance-operator/actions/runs/5895677716

Grant permissions required metal-toolbox workflow

---

pkg/controller/compliancescan/scan.go

This PR fixes issues on CSI driver relying on multipath, we need to set MountPropagation to HostToContainer to address this issue.
[OCPBUGS-17494](https://issues.redhat.com/browse/OCPBUGS-17494)

OCPBUGS-17494: Fix hostmount propagation

---

cmd/manager/operator.go
pkg/apis/compliance/v1alpha1/scansettingbinding_types.go

`go fmt` is fixing these when we run our tooling anyway. Let's commit
the changes so the tools don't dirty the repository.

Fix minor formatting issues

---

doc/usage.md

When using hypershift and scanning a hosted cluster, the namespace of the hosted cluster needs to be defined as well.
The namespace where clusters are installed can vary, and should be set accordingly for th scans to work.

Document namespace prefix when scanning a hosted cluster

---

enhancements/suspend-and-resume-scan-schedule.md

This commit includes an enhancement for implementing a feature that
pauses and resumes existing ComplianceScans.

Add enhancement for suspending and resuming scan schedules

---

doc/usage.md

The `must-gather` image's name is `must-gather-ocp`.
See https://github.com/orgs/ComplianceAsCode/packages?repo_name=compliance-operator

Docs: Fix URI for must-gather image

---

tests/e2e/framework/utils.go
tests/e2e/parallel/main_test.go

Since we're being explicit about which version we're using, let's make
sure we have a test for it.

Add an integration test to verify HTTP version usage

---

cmd/manager/fips.go

This commit does a few things to make sure the Compliance Operator is built
so that it can run in FIPS-enabled clusters.
- Uses ubi8-minimal for openssl for container image builds
- Set CGO_ENABLE=1
- Use a boilerplate base image for building the operator container image
- Set the appropriate flags so that go builds with FIPS enabled and
links dynamically to the necessary openssl libraries
- Includes a FIPS-enabled go source file that implements a "FIPS or Die"
feature
The ubi9-micro image we were using was ideal for minimal dependencies,
but it doesn't include openssl, which  we need to support FIPS. This
commit changes the operator container image to fix this.
Set CGO_ENABLE=1 so that go can link dynamically to the openssl library.
Use an image from app-sre/boilerplate to build the …

Build the operator for FIPS enabled environments

---

Makefile

Add the ability to pass in build flags (e.g., from Dockerfiles) in cases
were we need to specify them. For example, this can be useful for
enabling FIPS builds.

Implement build flags

---

CHANGELOG.md
bundle/manifests/compliance.openshift.io_compliancecheckresults.yaml
bundle/manifests/compliance.openshift.io_complianceremediations.yaml
bundle/manifests/compliance.openshift.io_compliancescans.yaml
bundle/manifests/compliance.openshift.io_compliancesuites.yaml
bundle/manifests/compliance.openshift.io_profilebundles.yaml
bundle/manifests/compliance.openshift.io_profiles.yaml
bundle/manifests/compliance.openshift.io_rules.yaml
bundle/manifests/compliance.openshift.io_scansettingbindings.yaml
bundle/manifests/compliance.openshift.io_scansettings.yaml
bundle/manifests/compliance.openshift.io_tailoredprofiles.yaml
bundle/manifests/compliance.openshift.io_variables.yaml
config/crd/bases/compliance.openshift.io_profiles.yaml
pkg/apis/compliance/v1alpha1/profile_types.go
pkg/profileparser/profileparser.go
tests/e2e/parallel/main_test.go

This commit adds support for an optional version attribute for Profile
custom resources. This attribute is parsed out of the datastream and set
on the Profile by the compliance operator. It's not intended for end
users to supply their own version.
Future patches may expand on this concept to support multiple versions
of a single profile.

CMP-2130: Implement support for profile versioning

---

bundle/manifests/compliance-operator.clusterserviceversion.yaml
config/manager/deployment.yaml
pkg/controller/profilebundle/profilebundle_controller.go

Drops caps and makes both run as non-root explicitly to suppress
warnings from PSA.

Harden the deployment and the profilebundle

---

CHANGELOG.md
cmd/manager/aggregator.go
config/rbac/remediation_aggregator_role.yaml
tests/e2e/framework/common.go
tests/e2e/parallel/main_test.go
tests/e2e/serial/main_test.go

Previously, the compliance operator would leave CCRs around and then
just overwrite them on subsequent scans. While the most recent scan data
was accurate, because it was overwriting existing check results, it gave
the impression that some changes weren't taking effect.
For example, if you create a tailored profile, run a scan, exclude a
rule, and rerun the scan, it appears the change you just made never took
effect because the result from the rule you ignored still exists.
To avoid this, let's check for any check results at scan time and make
sure we clean them up before we aggregate the new results.

OCPBUGS-3009: Prune stale CCRs before aggregating scan results

---

bundle/manifests/compliance-operator.clusterserviceversion.yaml

A recent change improved how the aggregator pod handled compliance check
results, by allowing it to find all existing results, and prune results
that were stale. This makes the state of the Compliance Check Results
consistent with the latest run:
https://github.com/ComplianceAsCode/compliance-operator/pull/221
To do this though, we needed to give the aggregator pod permissions to
list and delete Compliance Check Results. But, in that patch we forgot
to update the bundle build to include those new permissions. This means
bundle installs are currently broken for all scans because the
aggregator pod gets stuck in a crashloop, due to failing permissions.
This commit updates the manifest for the bundles so that bundle installs
work again.

CMP-3009: Update manifest to include new aggregator permissions

---

pkg/controller/compliancescan/forwarder.go

If a scan has debug enabled, the aggregator will log the remedation
information. Previously, you'd see a `dpanic` in the logs because the
keys passed into the logger were invalid.
This commit updates the logging implementation to use the correct key
pairs for the log.

Fix dpanic during remediation logging

---

tests/e2e/serial/main_test.go

We had OCPBUGS-8041, this commit corrected the expected status https://github.com/ComplianceAsCode/content/pull/11329

Fix e2e error

---

Makefile
config/manifests/bases/compliance-operator.clusterserviceversion.yaml
utils/get-current-version.sh

The `replaces` attribute of an operator's CSV helps OLM build
relationships between operators, making it easier for users to install
older versions of an operator (or know which version supercedes the
version they're using).
This commit reintroduces the `replaces` attribute, since it was being
deleted before as a side-effect of an operator-sdk update. It should be
safe to include again.

CMP-2176: Implement `replaces` in bundle CSV

---

.github/workflows/pr-image-trigger.yml
.github/workflows/release-pr.yml

Update the action to build image for each PR, so image can be built even when PR is created from a fork.

Update action workflows on PR image generation

---

pkg/controller/scansettingbinding/scansettingbinding_controller.go
pkg/controller/scansettingbinding/scansettingbinding_controller_test.go
tests/e2e/serial/main_test.go

This commit removes product validation in ScanSettingBinding so we can launch both `rhcos4` and `ocp4-node` scan in one SSB.
ex.
```
kind: ScanSettingBinding
metadata:
name: ocp4-rhcos4-moderate-mix
namespace: openshift-compliance
profiles:
- apiGroup: compliance.openshift.io/v1alpha1
kind: Profile
name: ocp4-moderate-node
- apiGroup: compliance.openshift.io/v1alpha1
kind: Profile
name: rhcos4-moderate
- apiGroup: compliance.openshift.io/v1alpha1
kind: Profile
name: ocp4-moderate
settingsRef:
apiGroup: compliance.openshift.io/v1alpha1
kind: ScanSetting
name: default
```

Remove product validation in ScanSettingBinding

---

pkg/controller/compliancesuite/compliancesuite_controller.go
tests/e2e/framework/common.go
tests/e2e/serial/main_test.go

This pr fixes a issue when a profile gets removed from scansettingbinding, the old scan was not deleted when a profile is removed from the existing scansettingbinding, this pr checks that and does the removal so that new scan using that profile can be launch correctly. check OCPBUGS-29272: https://issues.redhat.com/browse/OCPBUGS-29272

OCPBUGS-29272: Delete scan when SSB remove a profile

---

pkg/profileparser/profileparser.go

This ensures that rules part of STIG profile contain annotations with the STIGID.
One can see the STIG references as annotation on the rule when deployed together with content from https://github.com/ComplianceAsCode/content/pull/11593 
```
$ CONTENT_IMAGE=ghcr.io/complianceascode/k8scontent:11593 make deploy-local
$ oc get rule  ocp4-api-server-tls-security-profile -oyaml
...
metadata:
annotations:
compliance.openshift.io/image-digest: pb-ocp4vkwnn
compliance.openshift.io/profiles: ocp4-moderate-rev-4,ocp4-stig,ocp4-high-rev-4,ocp4-stig-v1r1,ocp4-moderate,ocp4-high,ocp4-nerc-cip
compliance.openshift.io/rule: api-server-tls-security-profile
control.compliance.openshift.io/NIST-800-53: SC-8;SC-8(1)
control.compliance.openshift.io/STIG: CNTR-OS-000020 …
```

CMP-2401: Add STIG reference parser

---

pkg/controller/compliancescan/scan.go

Let's stop removing the symlink when launching Node scans.
This allows multiple node scans to be launched without disrupting access to the kubelet config.

OCPBUGS-32216: Stop deleting the kubeletconfiglink

---

cmd/manager/operator.go

Add support to disable profilebundle creation based on architecture. Disable rhcos4 on ppc64le and s390x

Support disable profile bundle based on Arch

---

Makefile
pkg/utils/parse_arf_result_test.go

Add required test file so we can test if datastream can be parsed correctly by parser.

Add test file needed for testing CaC content

---

cmd/manager/scap.go
cmd/manager/scap_test.go
tests/data/empty_machineconfig.json

A jq filter may expect to iterate over a list of results, but it can happen that no result is returned.
Let's not fatal error when this happens.
In an HyperShift environment, when no MC config exists, the following error occurs:
```
$ oc logs pod/ocp4-pci-dss-api-checks-pod --all-containers
...
Fetching URI: '/apis/machineconfiguration.openshift.io/v1/machineconfigs'
debug: Applying filter '[.items[] | select(.metadata.name | test("^rendered-worker-[0-9a-z]+$|^rendered-master-[0-9a-z]+$"))] | map(.spec.fips == true)' to path '/apis/machineconfiguration.openshift.io/v1/machineconfigs'
debug: Error while filtering: cannot iterate over: null
debug: Persisting warnings to output file
FATAL:Error fetching resources: couldn't filter '{
"metadata": {},
"items": null 
}': cannot iterate over: …
```

OCPBUGS-33067: Don't fatal error when filter cannot iterate

---

cmd/manager/operator.go

We recently updated Compliance Operator support to only load ocp4
profiles when running on Power and Z systems, since those are currently
the only profiles that are supported on those architectures.
In the process, we added architecture detection so the operator knows if
it's running OpenShift on amd64, ppc64le, or s390x. However, the
operator will also create default scan settings based on the
architecture and platform, which didn't take these into account.
Since we were using new architecture/platform keys in the support
mapping, they weren't being handled correctly when the operator created
the default scan settings. This caused it to use a generic catch all to
schedule scans on all available nodes. While this is fine for some
platforms, like EKS, it doesn't work when nodes are in …

Fix platform role detection for Power and Z architecture

---

Makefile
tests/e2e/framework/common.go
tests/e2e/framework/framework.go
tests/e2e/rosa/main_test.go

We have to handle some differences in how we setup e2e testing on
managed OpenShift offerings, like ROSA. This commit stands up a separate
e2e suite that will be specific to ROSA test cases and wires it up to a
Makefile target for easy use.

CMP-2547: Implement ROSA e2e test suite

---

cmd/manager/operator.go
tests/e2e/framework/common.go
tests/e2e/rosa/main_test.go

Since the Compliance Operator is only going to support running on HCP environments, where end users don't have access to the master nodes (or control plane), it doesn't make sense to give them a scan setting with auto remediation functionality applied.
For this case, the Compliance Operator should detect if it is running on ROSA HCP and adjust, or just not create the `default-auto-apply` scan settings.

CMP-2526: Disable automatic remediation for ROSA HCP environments

---

pkg/profileparser/profileparser.go

We're seeing a panic in the log when parsing profiles on managed
offerings:
"msg":"odd number of arguments passed as key-value pairs for logging","ignored key"
This is likely related to https://github.com/ComplianceAsCode/compliance-operator/pull/518
This commit updates the log to use a key-value pair so that the panic
goes away.

Fix panic due to logging issue

---

tests/e2e/serial/main_test.go

Before, we were waiting for 30 minutes for a scan to timeout. 30 minutes
is a long time, and we have some retry logic in the operator to rekick
scans after a timeout. Let's reduce the timeout for tests to see if we
can improve resilience to flaky scans.

Reduce timeout from 30 minutes to 10 minutes in serial tests

---

Makefile
utils/get-current-version.sh

We need to be able to set the `replaces` attribute of the CSV file so
that OLM can build a relationship between dependencies, which is
important for disconnected installations and upgrades.
Previously, we were using the version in the CSV file, which worked but
it would change within the `make prepare-release` target depending on
when the command was invoked.
This commit updates the version script to use `git describe` instead,
which makes finding the current version more robust since tagging isn't
done until a subsequent step of the release process.

Use git describe for finding operator version

---

bundle/manifests/compliance-operator.clusterserviceversion.yaml
cmd/manager/operator.go
config/rbac/operator_cluster_role.yaml
pkg/controller/compliancescan/compliancescan_controller.go
pkg/controller/profilebundle/profilebundle_controller.go
pkg/profileparser/profileparser.go
pkg/utils/platform.go
tests/e2e/framework/common.go
tests/e2e/rosa/main_test.go

Let's ignore the case when comparing the case here, this should avoid issue if someone sets Platform environment to lower cased value. Such as rosa instead of ROSA.

OCPBUGS-34535: Ignore case when compare platform

---

.github/workflows/release-latest.yml
.github/workflows/release-pr.yml
cmd/manager/resultserver_test.go

Let's skip the result server rotating unit test for now on s390x so that we get a successful build.

Skip failed unit tests for s390x

---

.github/workflows/release.yml

Fixing multi-arch support for release image github workflow. Adding openscap image job to the release workflow.

Fixing release image multi-arch support

---

.github/workflows/release-latest.yml
.github/workflows/release-pr.yml

Let's remove the workaround since we have sbom issues fixed. ex:https://github.com/ComplianceAsCode/compliance-operator/actions/runs/9563061573/job/26377079635. This also adding the missing pr_number in the comment step.

Remove SBOM workaround

---

pkg/utils/parse_arf_result.go

This is to fix the rule instruction so that we can display as multiline string instead of pre-wrap text, and user is able to copy and run oc command in the instruction without having to remove escape. The issue was caused by space before newline made it not able to output multiline yaml formate.

OCPBUGS-17828: Fix rule instruction

---

pkg/controller/compliancescan/scan.go

* With `HostNetwork: true` the sysctl `net.core.bpf_jit_harden` becomes visible to the `scanner` container.
Below is a pod that has access to the sysctls:
```yaml 
apiVersion: v1
kind: Pod
metadata:
name: list-sysctls
spec:
hostNetwork: true
volumes:
- name: host
hostPath:
path: /
type: Directory
containers:
- name: list
command:
- cat
- /host/proc/sys/net/ipv6/conf/all/accept_ra
- /host/proc/sys/net/core/bpf_jit_harden
image: registry.access.redhat.com/ubi8/ubi-minimal
securityContext:
runAsUser: 0
privileged: true
volumeMounts:
- name: host
mountPath: /host
``` 
`$ oc create -f list-syctls-proc.yaml`
`$ oc logs list-sysctls `
* `DNSPolicy: ClusterFirstWithHostNet` allows the CO to upload to `resultserver`, otherwise we get the following error:
` …

OCPBUGS-19690: Enable host network to access host sysctls

---

bundle/manifests/compliance-operator.clusterserviceversion.yaml

Even though the must-gather plugin image isn't necessary for running the
operator, is helps users collect information when reporting issues.
By including the image reference in the `relatedImages` of the CSV, it's
more discoverable and users can query it out of the CSV directly,
instead of having to hunt through documentation and container
registries.

CMP-1096: Add must-gather image to relatedImages

---

doc/usage.md

Even though we documented using an image directly for must-gather support, we can also include the relatedImages reference in the usage guide.

CMP-2688: Document using relatedImages for must-gather

---

.github/workflows/container-scan-trivy.yml

Trivy is warning us about an issue in gosec where it thinks a secret is
being exposed, but it's actually just a regular expression. Let's
exclude it by the specific file that contains the violation so it stops
failing.

Fix false positive trivy filesystem scan result

---

tests/e2e/parallel/main_test.go

One of the parallel tests was using the name and description from
another test in its TailoredProfile. While this doesn't necessarily
cause issues, it can be confusing.
This commit updates the TailoredProfile name and title so they're
consistent with the test name.

Update TailoredProfile title description in parallel e2e

---

Makefile

The must-gather target had a reference to a non-existent target called
`must-gather-push`, which resulted in the following error when you
attempted to build the must-gather image locally:
make: *** No rule to make target 'must-gather-push', needed by 'must-gather'.  Stop.
This commit adds in the missing Makefile target to push the image to a
specific image registry so that you can build must-gather images locally
and push them to your own registry (e.g., useful for testing).

Add Makefile target for pushing must-gather image

---

doc/usage.md

The UI has changed to put metrics under Observe instead of Monitoring.
Update the documentation accordingly so it's accurate for readers today.

Update metrics navigation in documentation

---

config/rbac/operator_cluster_role.yaml

We have a rule in the compliance content that will check the
ingresscontroller's TLS ciphers. It also comes with a remediation to
update the ciphers so they're either Recommended or Secure. However,
the remediation errors out when it's loaded after a scan because the
Compliance Operator doesn't have the necessary permissions to get the
ingresscontrollers, or apply the remediation.
This commit updates the Compliance Operator's cluster role so that it
has the ability to update the TLS cipher configuration for
ingresscontrollers.

CMP-2196: Update cluster role permissions for ingresscontrollers

---

pkg/controller/compliancescan/scan.go

gofmt is attempting to fix formatting in scan.go. Pull this out in to a
separate change and clean it up.

:broom: Fix golang formatting in scan.go

---

doc/usage.md

We have an example in our documentation that tells users how to fetch
metrics using the command line. But, the command has a newline in the
middle of the authorization header, and if you copy/paste it from the
document, like most readers would, it returns an HTTP 404.
Remove the newline so the command works when you copy/paste it from the
documentation, which is the intention.

OCPBUGS-37697: Remove newline in metrics doc literal

---

.github/workflows/release-latest.yml

Previously, we were only updating the must-gather image when updating
specific must-gather files in utils and images. This commit adds it to
the release GitHub action so that it pushes a new container image for
each push to master, which should keep the image up-to-date.

Add must-gather image builds to release on each push

---

images/must-gather/Dockerfile.ocp

The image we were using wasn't accessible through GitHub actions,
because it's in a CI registry. Use an equivalent image from Quay so that
we can build must-gather images with GitHub actions.

Fix must-gather base image

---

.github/workflows/must-gather-latest.yml
.github/workflows/release-latest.yml

We're struggling to find a multi-arch image we can use for building the
must-gather image. This causes the GitHub action we have wired up to
build the image automatically to fail.
This commit removes power and z support for now so we can get some
builds produces that incorporate the new must-gather tooling.

Remove multi-arch support from must-gather image

---

config/rbac/api_resource_collector_cluster_role.yaml

with https://github.com/ComplianceAsCode/content/pull/11997 the compliance-operator needs read access to kubedescheduler resources for the validation. We do this on clusterlevel, as the namespaces where the kubedescheduler can be deployed is configurable
this PR supersedes https://github.com/ComplianceAsCode/compliance-operator/pull/519

Add kubedeschedulers to api_resource_collector_clusterrole

---

utils/must-gather/gather_compliance

Events are really helpful in debugging what's happening in the
openshift-compliance namespace. Add them to the must-gather image so
they get populated in must-gather reports by default.

Add events to must-gather image

---

.github/workflows/pr-image-trigger.yml
.github/workflows/release-pr.yml

Let's use commit pr-number-commit-sha as the image tag for the image built for the PR, also use the label to build an image other than amd64 for s390x and ppc64le, for example adding `arch/ppc64le` or `arch/ppc64le` label to the PR to build for ppc64le and s390x

Add commit-sha into pr image build

---

pkg/profileparser/profileparser.go

This ensures the rules part of PCI-DSS v4 profile contains annotations with supported requirement number.
```
$ CONTENT_IMAGE=ghcr.io/complianceascode/k8scontent:12309 make deploy-local
$ oc get rule ocp4-api-server-tls-cert -oyaml
...
id: xccdf_org.ssgproject.content_rule_api_server_tls_cert
kind: Rule
metadata:
annotations:
compliance.openshift.io/image-digest: pb-upstream-ocp45qsp7
compliance.openshift.io/profiles: upstream-ocp4-high,upstream-ocp4-nerc-cip,upstream-ocp4-cis-1-4,upstream-ocp4-moderate-rev-4,upstream-ocp4-cis,upstream-ocp4-cis-1-5,upstream-ocp4-moderate,upstream-ocp4-pci-dss,upstream-ocp4-pci-dss-3-2,upstream-ocp4-high-rev-4,upstream-ocp4-pci-dss-4-0
compliance.openshift.io/rule: api-server-tls-cert
control.compliance.openshift.io/CIS-OCP: 1.2.28 …
```

Add PCI-DSS v4.0 reference parser

---

bundle/manifests/compliance-operator.clusterserviceversion.yaml

The github action we have for making sure we update the bundle in PRs
broke, causing some changes to slip into the operator without updating
the bundle manifests.
This commit updates the bundle by running `make verify-bundle` then
committing the changes.
The manifests changes reflect updates we made to the operator so that it
has the necessary permissions for ingresscontrollers and
kubedeschedulers.

Update bundle manifests

---

.github/workflows/bundle_tests.yaml

The bundle test action has been failing with:
Error
Invalid type for `on`
This commit attempts to fix that by updating the `on` configuration to
use branches, which is what we do elsewhere in our actions.

Fix GHA for bundle tests

---

bundle/manifests/compliance-operator.clusterserviceversion.yaml
config/manifests/bases/compliance-operator.clusterserviceversion.yaml

Since we have a must-gather image, we should advertise that information
through the bundle. We typically do this using `RELATED_IMAGES`, which
the operator uses to find container images it needs to do things like
profile parsing or scanning.
While we can use `RELATED_IMAGES` for the must-gather image, the
Compliance Operator doesn't use the must-gather image directly. Instead,
we can put it in the annotation of the bundle CSV, so it's still
discoverable to users, while not polluting the operator environment with
variables it doesn't need.

Update bundle annotations to include must-gather image

---

cmd/manager/aggregator.go
cmd/manager/common.go
pkg/apis/compliance/v1alpha1/compliancecheckresult_types.go
tests/e2e/framework/common.go
tests/e2e/parallel/main_test.go

Adding the lastscanned timestamp annotation in each `complianceCheckResult`, added annotation `compliance.openshift.io/last-scanned-timestamp` with a value equal to `scan.status.StartTimestamp`
example of CCR
```yaml
kind: ComplianceCheckResult
metadata:
annotations:
compliance.openshift.io/last-scanned-timestamp: "2024-08-15T04:26:11Z"
compliance.openshift.io/rule: scc-limit-root-containers
creationTimestamp: "2024-08-15T04:26:43Z"
generation: 1
labels:
compliance.openshift.io/check-severity: medium
compliance.openshift.io/check-status: MANUAL
compliance.openshift.io/profile-guid: a230315d-3e4a-5b58-b00f-f96f1553e036
compliance.openshift.io/scan-name: ocp4-cis
compliance.openshift.io/suite: ocp4-cis-ssb
name: ocp4-cis-scc-limit-root-containers
namespace: openshift-compliance
```
```yaml …
```

CMP-2614: Implement update timestamps on ComplianceCheckResults

---

pkg/apis/compliance/v1alpha1/compliancescan_types.go
pkg/controller/compliancescan/compliancescan_controller.go
tests/e2e/framework/common.go
tests/e2e/framework/utils.go
tests/e2e/serial/main_test.go

Implement a total check count as an annotation of the ComplianceScan, we will add an annotation `compliance.openshift.io/check-count` to every `compliancescan` object when a scan is in `Done` state. 
Noted: This annotation is removed when a new scanPhase begins.
example of output
```yaml
[vincent@node test-file]$ oc get scan ocp4-cis -o yaml
kind: ComplianceScan
metadata:
annotations:
compliance.openshift.io/check-count: "89"
creationTimestamp: "2024-08-15T04:42:36Z"
finalizers:
- scan.finalizers.compliance.openshift.io
generation: 1
labels:
compliance.openshift.io/profile-guid: a230315d-3e4a-5b58-b00f-f96f1553e036
compliance.openshift.io/suite: ocp4-cis-ssb
name: ocp4-cis
```

CMP-2615: Add a check aggregate to the compliance scan metadata

---

bundle/manifests/compliance-operator.clusterserviceversion.yaml
config/manifests/bases/compliance-operator.clusterserviceversion.yaml
config/rbac/api_resource_collector_cluster_role.yaml

In cluster logging operator 6.0 the `ClusterlogForwarder` moved from `logging.openshift.io` to `observability.openshift.io`.
CO will need to access `ClusterlogForwarder` from both APIs.

Allow access to clusterlogforwarder in observability API

---

images/operator/Dockerfile

This dockerfile contains the necessary labels to build the operator for
a bundle build, which we'll wire up to Konflux.

Add operator dockerfile for Konflux builds

---

images/operator/Dockerfile

Konflux is erroring out because the system is already registered, even
though it's from a previous container. Remove the second subscription
registration so that we don't error out installing dependencies we need
for the operator container image.

Remove unnecessary subscription from operator Dockerfile

---

Dockerfile.ci

The 4.17 builder image doesn't exist for golang 1.23. Instead, there is
one for 4.19, so let's use that so we can bump to golang 1.23.

Fix OCP reference in golang builder image

---

images/operator/Dockerfile

We recently made some changes to use golang 1.23, but we didn't include the Konflux docker files.
This commit bumps the golang builder image to use golang 1.23 which is what we're using in CI and in go.mod.

Update Konflux docker file to use golang 1.23

---

bundle/manifests/compliance-operator.clusterserviceversion.yaml
config/manifests/bases/compliance-operator.clusterserviceversion.yaml
images/testcontent/new_kubeletconfig/ssg-ocp4-ds.xml
tests/data/ssg-ocp4-ds-suppressed.xml

The old link pointed to a section of the compliance operator documentation before it was overhauled and reorganized.
This commit updates the documentation reference in the bundle so it points to the right document, and doesn't return a 404.

Fix broken docs link in the Compliance Operator bundle

---

.tekton/compliance-operator-must-gather-pull-request.yaml
.tekton/compliance-operator-must-gather-push.yaml
.tekton/compliance-operator-openscap-pull-request.yaml
.tekton/compliance-operator-openscap-push.yaml
.tekton/compliance-operator-pull-request.yaml
.tekton/compliance-operator-push.yaml
images/must-gather/Containerfile
images/must-gather/rpms.in.yaml
images/must-gather/rpms.lock.yaml
images/openscap/rpms.in.yaml
images/openscap/rpms.lock.yaml
images/operator/Dockerfile
images/operator/rpms.in.yaml
images/operator/rpms.lock.yaml
redhat.repo

This commit introduces a lock file for RPMs so that we can produce
hermetic builds with Konflux, following the guidance in documentation:
https://github.com/konflux-ci/docs/pull/192

Add lock file for RPMs to enable hermetic builds

---

Makefile
bundle/manifests/compliance-operator.clusterserviceversion.yaml
catalog/preamble.json
config/manifests/bases/compliance-operator.clusterserviceversion.yaml
version.Makefile

- **Bump CO version for 1.6.2 development**
- **Use make to set versions in manifests**
- **Update manifests to include 1.6.2-dev**

bump co version 1.6.2 dev

---

.github/workflows/test-broken-content-latest.yml

TestManualRulesTailoredProfile is failing on arm64 clusters because the
test content we're using isn't built for arm64, resulting in the
following test case error:
waiting ProfileBundle test-manual-rules-tailored-profile to become VALID (INVALID)
ProfileBundle test-manual-rules-tailored-profile failed to reach state VALID
This commit updates the github action we use to build the test image so
that it starts building for arm64.

Build test content using arm64

---

.github/workflows/test-broken-content-latest.yml

This commit updates the test-broken-content-latest github action so that
it will rebuild the test content when the action is changed or updated.
This means we don't need to look for minor changes to make in the
images/testcontent directory each time we want to incorporate a change
into the image becuase the workflow changed.

Run test-broken-content-latest action when updated

---

bundle/manifests/compliance-operator.clusterserviceversion.yaml
config/manifests/bases/compliance-operator.clusterserviceversion.yaml
config/rbac/api_resource_collector_cluster_role.yaml

This PR adds permissions to read the kataconfigs for the api-resource-collector.
This is related to a complianceascode/content PR which checks, that a proper isolation between containers is guaranteed
first I only changed the file under config/rbac but this let the tests fail. so I followed what was done in:
https://github.com/ComplianceAsCode/compliance-operator/commit/90eb2a7d38700266b6bd9a02a537323dc8c0e026
this might or might not be the correct way, but fixes the failing test :)

add read permission for kataconfig

---

.github/workflows/release-pr.yml

Our github action to build images for each PR for testing was failing
with the following trace:
Warning: Unexpected input(s) 'pr_number', valid inputs are ['message',
'file-path', 'github-token', 'reactions', 'pr-number', 'comment-tag',
'mode', 'create-if-not-exists']
I think this was causing the job to fail because it wasn't getting the
PR number to leave the comment:
Error: No issue/pull request in input neither in current context.
This commit attempts to fix this issue by using the correct key
(pr-number).

Fix Release Image Action

---

.github/workflows/release-latest.yml
.github/workflows/release.yml

If we want to test on arm64, we'll need to configure our actions to
build for that architecture.

Update release actions to build images for ARM64

---

.github/workflows/release-latest.yml

https://github.com/ComplianceAsCode/compliance-operator/pull/679 added
support for building arm64 images, but breaks with the must-gather image
because it uses quay.io/openshift/origin-cli:latest, which doesn't have
an arm64 build:
ERROR: failed to solve: quay.io/openshift/origin-cli:latest: failed to
resolve source metadata for quay.io/openshift/origin-cli:latest: no
match for platform in manifest: not found
Backout this change so the Release Latest workflow doesn't fail on
must-gather builds.

Revert arm64 support for must-gather image

---

tests/e2e/framework/utils.go
tests/e2e/parallel/main_test.go

Wrap the `GetPrometheusMetricTargets` call with wait.Poll so it retries on transient oc command failures, preventing the `error getting output: exit status 1` failures
[OCPBUGS-48461](https://issues.redhat.com/browse/OCPBUGS-48461)

OCPBUGS-48461: enhance error handling for PrometheusMetricTargets

---

.github/workflows/check-pr-title.yaml

This makes it so we have an action that will fail if the PR doesn't
reference a Jira ticket, helping us track work in the repository to
items in Jira.

CMP-3152: Implement an action to check PR titles

---

pkg/controller/compliancescan/compliancescan_controller.go
pkg/controller/compliancescan/compliancescan_controller_test.go

We were doing two updates without re‐fetching. This fixes it by ensuring we re-fetch before going to do the next step.
This will help with the stability of the controller logic.

OCPBUGS-51267: Fix an issue in the ComplianceScan controller

---

Makefile

We're seeing arm64 builds timeout because 10 minutes isn't enough time
to run the unit tests. However, when testing this on a native arm64
machine, the run time difference is negligible. One possibility is that
because the Github Action runner is using amd64 under the hood, it's
taking longer to cross-compile and build for arm64.
This commit doubles the unit test timeout from 10m to 20m to see if this
helps improve arm64 build stability.

CMP-3121: Increase unit test timeout to 20 minutes

---

tests/e2e/framework/common.go

We should not expect checkCount to be unset during PhaseAggregating, because we are setting the checkcount during that phase, this might casue transient issues in between the waiting period

CMP-3155: Fix e2e test for checkcount

---

pkg/profileparser/profileparser.go

This adds BSI to the standards annotation:
`policies.open-cluster-management.io/standards: BSI`
And adds the requirement number to the following annotaions::
- `control.compliance.openshift.io/BSI`
- `policies.open-cluster-management.io/controls`
For example:
`$ oc get rule upstream-ocp4-kubeadmin-removed -oyaml`
```yaml
...
kind: Rule
metadata:
annotations:
compliance.openshift.io/image-digest: pb-upstream-ocp49577j
compliance.openshift.io/profiles: upstream-ocp4-high-rev-4,upstream-ocp4-pci-dss,upstream-ocp4-high,upstream-ocp4-pci-dss-3-2,upstream-ocp4-cis-1-4,upstream-ocp4-cis-1-5,upstream-ocp4-cis,upstream-ocp4-stig-v1r1,upstream-ocp4-nerc-cip,upstream-ocp4-bsi,upstream-ocp4-bsi-2022,upstream-ocp4-moderate-rev-4,upstream-ocp4-moderate,upstre …
```

Add BSI reference parser

---

pkg/apis/compliance/v1alpha1/profilebundle_types.go
pkg/controller/compliancescan/compliancescan_controller.go
pkg/controller/compliancescan/compliancescan_controller_test.go
pkg/controller/tailoredprofile/tailoredprofile_controller.go
pkg/profileparser/profileparser.go
pkg/xccdf/tailoring.go
tests/e2e/framework/common.go
tests/e2e/parallel/main_test.go
tests/e2e/serial/main_test.go

The Content Profiles can now be set as deprecated.
The Compliance Operator needs to be able to identify them and warn users of the need to make adjustments.
- When Parsing Content, it annotates deprecated profiles with `compliance.openshift.io/profile-status: deprecated`
- Whenever a `ComplianceScan` is started using a deprecated profile we add a warning to the object.
- - From the `ComplianceScanSpec`, it find the `ProfileBundle` that matches the `ContentImage` and `ContentFile`. 
Once a matching `ProfileBundle` is found it simply grabs the profile whose ID matches the `ComplianceScanSpec` and checks for its deprecated annotation.

CMP-3149: Handle profile deprecation

---

bundle/manifests/compliance-operator.clusterserviceversion.yaml
config/manifests/bases/compliance-operator.clusterserviceversion.yaml

This commit implements support for running the Compliance Operator on
ARM64 architecture.

CMP-3117: Add arm64 label to bundle CSV

---

pkg/profileparser/profileparser.go

The NERC-CIP references in the ComplianceAsCode/content were updated
recently because they were pointing to a dead link (HTTP 404).
https://github.com/ComplianceAsCode/content/pull/12892
This commit updates the profile parser to use the same link. Without
doing this, the rules won't contain annotations or controls for the
NERC-CIP profile, even though the Compliance Operator has a profile for
it.

OCPBUGS-55181: Update NERC-CIP reference

---

.github/workflows/test-broken-content-latest.yml

If we don't do this, the action will run for older branches which might
not contain all the architectures we currently support.

CMP-3138: Only build broken test content on master

---

pkg/controller/tailoredprofile/tailoredprofile_controller.go
pkg/controller/tailoredprofile/tailoredprofile_controller_test.go
tests/e2e/framework/common.go
tests/e2e/parallel/main_test.go

Implement duplicate detection for setValues in TailoredProfile and add warning event [OCPBUGS-11228](https://issues.redhat.com/browse/OCPBUGS-11228)

OCPBUGS-11228: Check for duplicate variables in TailoredProfile
